CREATE TABLE IF NOT EXISTS users
(
    id          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id     VARCHAR(20) UNIQUE NOT NULL,
    password    VARCHAR(30) NOT NULL,
    playtime    INT DEFAULT 0,
    last_login  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);